
name: Lab Test Workflow

on:
  push:
    branches:
      - main

jobs:
  test-lab:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create test file
        run: |
          echo "hello lab" > test.txt

      - name: Show file content
        run: |
          cat test.txt
