

name: Deploy After Merge

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create test file
        run: |
          echo "hello lab" > test.txt

      - name: Show file content
        run: |
          cat test.txt

      - name: Deploy
        run: |
          echo "Deploying..."
